### ISSUE TITLE
Leave self closing tags.

### ISSUE THREAD

**Issue by jdalton** [t1st3/muxml#18]
Currently self closing tags like `<somethingLong value="b"/>`
are expanded to `<somethingLong value="b"></somethingLong>`.

**Comment by t1st3** [comment]
Hi @jdalton, thanks for reporting this and sorry for my late answer.
At the moment, as this module relies on `sax` to parse XML, it follows its behavior regarding self-closing tags; here is `sax`'s documentation excerpt about this:
_In loose mode, tags are auto-closed if their parent closes. In strict mode, well-formedness is enforced. Note that self-closing tags will have closeTag emitted immediately after openTag. Argument: tag name._
That said, I'm going to look for a way to keep self closing tags rather than expanding them.

**Comment by t1st3** [comment]
This is now fixed, and released under 0.2.1.
Thanks @jdalton

**Comment by jdalton** [comment]
❤️

**Comment by jdalton** [comment]
Could you bump gulp-muxml to take advantage of it too. The current published one is pulling down `muxml` v0.1.3.

**Comment by t1st3** [comment]
Just released a new version of `gulp-muxml` (0.1.2) including the fix.
I'm on it also for `muxml-cli` and `grunt-muxml`.
Thanks for your feedback, it's much appreciated!

**Comment by t1st3** [comment]
All done! (`muxml-cli` published as 0.1.5 and `grunt-muxml` published as 0.1.3)
